{% set version = '0.4-12' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-quantmod
  version: {{ version|replace("-", "_") }}

source:
  fn: quantmod_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/quantmod_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/quantmod/quantmod_{{ version }}.tar.gz
  sha256: 18d61d869180670cd5e97bc6cc12ab2939b8b63ae720c89c6e1b041d2680ef78


  # patches:
   # List any patch files here
   # - fix.patch

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0


  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: DBI,RMySQL,RSQLite,timeSeries,XML,downloader,jsonlite(>= 1.1)
requirements:
  build:

  host:
    - r-base
    - r-ttr >=0.2
    - r-curl
    - r-xts >=0.9_0
    - r-zoo

  run:
    - r-base
    - r-ttr >=0.2
    - r-curl
    - r-xts >=0.9_0
    - r-zoo

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('quantmod')"           # [not win]
    - "\"%R%\" -e \"library('quantmod')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: http://www.quantmod.com https://github.com/joshuaulrich/quantmod
  license: GPL-3
  summary: Specify, build, trade, and analyse quantitative financial trading strategies.
  license_family: GPL3

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: quantmod
# Type: Package
# Title: Quantitative Financial Modelling Framework
# Version: 0.4-12
# Date: 2017-12-02
# Authors@R: c( person(given=c("Jeffrey","A."), family="Ryan", role=c("aut","cph")), person(given=c("Joshua","M."), family="Ulrich", role=c("cre","aut"), email="josh.m.ulrich@gmail.com"), person(given="Wouter", family="Thielen", role="ctb"), person(given="Paul", family="Teetor", role="ctb") )
# Depends: R (>= 3.2.0), xts(>= 0.9-0), zoo, TTR(>= 0.2), methods
# Imports: curl
# Suggests: DBI,RMySQL,RSQLite,timeSeries,XML,downloader,jsonlite(>= 1.1)
# Description: Specify, build, trade, and analyse quantitative financial trading strategies.
# LazyLoad: yes
# License: GPL-3
# URL: http://www.quantmod.com https://github.com/joshuaulrich/quantmod
# BugReports: https://github.com/joshuaulrich/quantmod/issues
# NeedsCompilation: no
# Packaged: 2017-12-02 16:45:04 UTC; josh
# Author: Jeffrey A. Ryan [aut, cph], Joshua M. Ulrich [cre, aut], Wouter Thielen [ctb], Paul Teetor [ctb]
# Maintainer: Joshua M. Ulrich <josh.m.ulrich@gmail.com>
# Repository: CRAN
# Date/Publication: 2017-12-10 17:13:49 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
