travis:
  secure:
    BINSTAR_TOKEN: dK1jrCqlcgWcq3a/w8T3kOvEV4Mz1TH8jWNZMypDa2aQDw2lMx72d/z2AHCL3DA6lQt6ETaW+1sIYN7g1IeD5JGUHCNXKpmRWy7NESq0rpBm4VRiqGN90YSkYa0t4FiUxdG4LwXEYShFdmOJOIxiNmHns+ZcPgZNFTmGMFsgp7dwTRyEYfnKYTH5IcA/rcwZQqzURCyAkSodeybwEc8e8kiEyB/XpwzYTDdLbQsBB784n14aVu8zZL+mo7/WsptbIv8VIPF+c6VzWFsqp3as6o73f0JybS+OFf+AOA7y6+Ke166IEJ1CqtVcVTz7T64a8bw0Na61Azn3A8D/StNIMOF0ryBDXUeZmhFL9+GR31d53wVIkk7/bmvhEYVt0yTT3243cFq8eeGcBeYJJjW/rGfHoCScAf8FNw3GHa7c5Wp1Hlpnr5WZjV6NTmNEdtPudxpfUayMgfITQiz1T+rQmN8wogIOGl99MD877PTPG/Ujh+ZRMwdJUnnGvq7ujynanpcKYNy1WCQOe531dsbk2MFBshLSWdEEtOaKZox2nIF/cmAyiST/OAAzrCu7vQmVgXTlyocvaDqR2T4mLEQXLWujrZZKRBoByHwz0etZxNzaiNL8lq5zPNhtow9L+FqklSceWIeFhIfy7tsiXgJJtgNuBrhec69tnqv+m3cs5Ag=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
